services:
  alist:
    image: xhofe/alist
    container_name: alist
    restart: always
    ports:
    - 5244:5244
    volumes:
    - alist-data:/opt/alist/data
    environment:
    - PUID=0
    - PGID=0
    - UMASK=022

volumes:
  alist-data:
    name: alist-data
