version: '3.5'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db
  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
    - 6379:6379
    volumes:
    - redis-data:/data

volumes:
  postgres-data:
    name: postgres-data
  redis-data:
    name: redis-data
  mongo-data:
    name: mongo-data
