version: '3.5'

services:
  lanraragi:
    image: difegue/lanraragi
    container_name: lanraragi
    restart: always
    ports:
    - 8082:3000
    volumes:
    - f:\lanraragi:/home/koyomi/lanraragi/content
    - lanraragi-data:/home/koyomi/lanraragi/database

volumes:
  lanraragi-data:
    name: lanraragi-data
    external: true
