version: '3.5'

services:
  nocodb:
    image: nocodb/nocodb
    container_name: nocodb
    restart: always
    ports:
    - 8081:8080
    environment: 
      NC_DB: "pg://postgres:5432?u=postgres&p=postgres&d=database"
    volumes:
    - nocodb-data:/usr/app/data

volumes:
  nocodb-data:
    name: nocodb-data
