version: '3.5'

services:
  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: always
    ports:
    - 1200:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: redis://redis:6379/
      PUPPETEER_WS_ENDPOINT: ws://browserless:3000
      # PROXY_URI: socks5h://warp-socks:9091
